# Tensor Operations

## Function that help in creating tensors
<html>
    <body>
       <ul>
           <li>torch.rand()</li>
           <li>torch.randn()</li>
           <li>torch.randperm()</li>
           <li>torch.ones()</li>
           <li>torch.zeros()</li>
           <li>torch.eye()</li>
        </ul>
    </body>
</html>

In [1]:
#importing torch and other related modules
import torch

# 01.torch.rand

Creates a tensor of given shape and fills it with random values between 0-1 and follows uniform distribution

In [2]:
x = torch.rand(2,3)
x

tensor([[0.6240, 0.2592, 0.4763],
        [0.5479, 0.6646, 0.2756]])

In [3]:
y = torch.rand(1,4)
y

tensor([[0.4680, 0.1004, 0.5716, 0.6484]])

In [6]:
#z = torch.rand() # Breaks when no arguments are given


# 02.torch.randn

creates a tensor of given shape and fills it with random values but follows normal distribution

In [13]:
x = torch.randn(2,3)
x

tensor([[-1.2854,  1.0834, -0.3618],
        [-1.0170,  0.1447, -1.0545]])

In [14]:
y = torch.randn(1,4)
y

tensor([[ 0.5094,  0.6347, -0.2230, -2.9865]])

In [15]:
#z = torch.randn()# Breaks when no arguments are given

# 03.torch.randperm

creates a tensor of permutation from 0 to size n-1

In [19]:
x = torch.randperm(5)
x

tensor([4, 3, 1, 0, 2])

In [20]:
y = torch.randperm(10)
y

tensor([9, 8, 0, 7, 1, 4, 2, 3, 6, 5])

In [26]:
#z = torch.randperm(1,2) # Breaks when arguments are not one 

# 04.torch.ones

Creates a tensor of given shape and fill it with ones

In [34]:
x = torch.ones(4,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [35]:
y = torch.ones(2,3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
#z = torch.ones()
#Breaks when no arguments are given

# 05.torch.zeros

Creates a tensor of given shape and fill it with zeros

In [39]:
x = torch.zeros(4,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [40]:
y = torch.zeros(2,3)
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [41]:
# z = torch.zeros()
# Breaks when no arguments are given

# 06.torch.eye

creates a identity matrix of size n

In [42]:
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [44]:
y =torch.eye(2)
y

tensor([[1., 0.],
        [0., 1.]])

In [46]:
#z = torch.eye()
#Breaks when no arguments are given

In [ ]:
import jovian
jovian.commit()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
